### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by wvsonp** [simongrest/farm-pin-crop-detection-challenge#2]
When I try to run this cell: Plot average NDVI I get the error: AttributeError: 'PosixPath' object has no attribute 'startswith'. 
All library are installed.
This is the entire error:

AttributeError                            Traceback (most recent call last)
<ipython-input-18-6e42c75d9f54> in <module>
----> 1 eopatch = EOPatch.load(patch_path/f'eopatch_11', lazy_loading=True)
      2 
      3 plt.figure(figsize=(20,8))
      4 
      5 ax = plt.subplot(1, 3, 1)
~/anaconda3/lib/python3.7/site-packages/eolearn/core/eodata.py in load(path, features, lazy_loading, filesystem)
    523         """
    524         if filesystem is None:
--> 525             filesystem = get_filesystem(path, create=False)
    526             path = '/'
    527 
~/anaconda3/lib/python3.7/site-packages/eolearn/core/fs_utils.py in get_filesystem(path, create, **kwargs)
     26     :rtype: fs.FS
     27     """
---> 28     if path.startswith('s3://'):
     29         return load_s3_filesystem(path, *kwargs)
     30 
AttributeError: 'PosixPath' object has no attribute 'startswith'

**Comment by simongrest** [comment]
It seems like eo-learn is expecting a string argument for the path parameter in the load() method - at the moment a Path object is being passed in. Perhaps try explicitly converting it first? So maybe try 

`eopatch = EOPatch.load(str(patch_path/f'eopatch_{idx}'), lazy_loading=True)`?

**Comment by ces0008** [comment]
The problem exist and above trick doesn't seem to be working.
The other libraries are using fs_utils.py in eolearn.core which even I tried to put str(path).startswith.... in there but it doesn't help.  
the following lines are generated in report.html file after running the execution cell.
`
 Traceback (most recent call last):   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/eotask.py", line 72, in _execute_handling     return_value = self.execute(*eopatches, **kwargs)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/core_tasks.py", line 119, in execute     eopatch.save(path, filesystem=self.filesystem, **self.kwargs)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/core_tasks.py", line 74, in filesystem     self._filesystem = get_filesystem(self.path, create=self._create)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/fs_utils.py", line 28, in get_filesystem     if path.startswith('s3://'): AttributeError: 'PosixPath' object has no attribute 'startswith'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/eoexecution.py", line 189, in _execute_workflow     results = workflow.execute(input_args, monitor=True)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/eoworkflow.py", line 172, in execute     results = WorkflowResults(self._execute_tasks(input_args=input_args, out_degs=out_degs, monitor=monitor))   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/eoworkflow.py", line 210, in _execute_tasks     monitor=monitor)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/eoworkflow.py", line 243, in _execute_task     return task(*inputs, **kw_inputs, monitor=monitor)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/eotask.py", line 59, in __call__     return self._execute_handling(*eopatches, **kwargs)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/eotask.py", line 85, in _execute_handling     raise extended_exception.with_traceback(traceback)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/eotask.py", line 72, in _execute_handling     return_value = self.execute(*eopatches, **kwargs)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/core_tasks.py", line 119, in execute     eopatch.save(path, filesystem=self.filesystem, **self.kwargs)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/core_tasks.py", line 74, in filesystem     self._filesystem = get_filesystem(self.path, create=self._create)   File "/home/azizi/anaconda3/envs/farm/lib/python3.7/site-packages/eolearn/core/fs_utils.py", line 28, in get_filesystem     if path.startswith('s3://'): AttributeError: During execution of task SaveToDisk: 'PosixPath' object has no attribute 'startswith'
`

**Comment by farliz** [comment]
I use this way and work ok.

`eopatch = EOPatch.load(str(INPUT_EOPATCH), lazy_loading=True)`

**Comment by manojparmar968** [comment]
Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 257, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/core/management/commands/populate_products.py", line 2, in <module>
    from faker import Faker
  File "/usr/local/lib/python3.9/site-packages/faker/__init__.py", line 1, in <module>
    from faker.factory import Factory
  File "/usr/local/lib/python3.9/site-packages/faker/factory.py", line 7, in <module>
    from faker.config import AVAILABLE_LOCALES, DEFAULT_LOCALE, PROVIDERS
  File "/usr/local/lib/python3.9/site-packages/faker/config.py", line 11, in <module>
    PROVIDERS = find_available_providers(
  File "/usr/local/lib/python3.9/site-packages/faker/utils/loading.py", line 57, in find_available_providers
    for mod in list_module(providers_mod) if mod != '__pycache__'
  File "/usr/local/lib/python3.9/site-packages/faker/utils/loading.py", line 35, in list_module
    return [name for _, name, is_pkg in pkgutil.iter_modules([path]) if is_pkg]
  File "/usr/local/lib/python3.9/site-packages/faker/utils/loading.py", line 35, in <listcomp>
    return [name for _, name, is_pkg in pkgutil.iter_modules([path]) if is_pkg]
  File "/usr/local/lib/python3.9/pkgutil.py", line 130, in iter_modules
    for i in importers:
  File "/usr/local/lib/python3.9/pkgutil.py", line 420, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1601, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1476, in __init__
  File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'

any solution
